import pandas as pd
import numpy as np

def audit_nlp_pillars(loader, df_processed):
    """
    Performs a structural and semantic audit of the NLP pillars
    generated by the ClinicalTrialLoader.
    """
    print("="*80)
    print("NLP PILLAR AUDIT REPORT")
    print("="*80)

    # 1. Column Existence Check
    required_pillars = ['txt_scientific_essence', 'txt_criteria', 'txt_primary_endpoints']
    missing = [col for col in required_pillars if col not in df_processed.columns]

    if not missing:
        print("[SUCCESS] All NLP Pillars are present in the DataFrame.")
    else:
        print(f"[FAILURE] Missing Pillars: {missing}")

    # 2. Sanitization Check (The "No NaN" Rule)
    print("\n>>> Checking Sanitization (Null Handling):")
    for col in required_pillars:
        null_count = df_processed[col].isna().sum()
        # Check for string 'nan' which is a common Pandas bug
        string_nan_count = (df_processed[col] == 'nan').sum()

        if null_count == 0 and string_nan_count == 0:
            print(f"  - {col}: Clean (0 nulls, 0 'nan' strings)")
        else:
            print(f"  - {col}: WARNING! Found {null_count} nulls and {string_nan_count} 'nan' strings.")

    # 3. Structural Audit (The [SEP] Token Check)
    print("\n>>> Checking Pillar Structure (Separator Logic):")
    # Pillar A should have two [SEP] tokens (Title [SEP] Summary [SEP] Keys)
    sample_essence = df_processed['txt_scientific_essence'].iloc[0]
    sep_count = sample_essence.count("[SEP]")
    print(f"  - Pillar A ([SEP] count): {sep_count} (Expected: 2 if all data present)")

    # 4. Leakage & Cleanup Audit
    print("\n>>> Checking Cleanup (Raw Column Removal):")
    forbidden = ['official_title', 'temp_summary', 'criteria', 'temp_keys', 'why_stopped']
    found_forbidden = [col for col in forbidden if col in df_processed.columns]

    if not found_forbidden:
        print("  - Cleanup: SUCCESS (All raw/leakage columns dropped)")
    else:
        print(f"  - Cleanup: FAILURE (Found forbidden columns: {found_forbidden})")

    # 5. Visual Sample for Manual Review
    print("\n>>> Sample Data (First Row):")
    for col in required_pillars:
        content = df_processed[col].iloc[0]
        # Truncate for display
        display_content = (content[:100] + '...') if len(content) > 100 else content
        print(f"  - {col}: {display_content}")
    print("="*80)
