import pandas as pd
import numpy as np
from src.data.preprocessing import get_preprocessor

def generate_realistic_mock_data(n_rows=50):
    """Generates data that looks like your real Clinical Trial data."""
    np.random.seed(42)

    data = {
        # --- Skewed Numerics (to test Log1p) ---
        'competition_broad': np.random.exponential(scale=100, size=n_rows), # Long tail
        'competition_niche': np.random.exponential(scale=20, size=n_rows),
        'num_primary_endpoints': np.random.randint(1, 10, size=n_rows),
        'number_of_arms': np.random.randint(1, 5, size=n_rows),

        # --- Normal Numerics (to test StandardScaler) ---
        'start_year': np.random.randint(2005, 2020, size=n_rows),
        'design_rigor_score': np.random.randint(0, 6, size=n_rows),
        'eligibility_strictness_score': np.random.normal(2, 1, size=n_rows),
        'criteria_len_log': np.random.normal(7, 1, size=n_rows),

        # --- Categoricals (to test OneHot) ---
        'agent_category': np.random.choice(['KINASE_INHIBITOR', 'BIOLOGIC', 'VACCINE'], size=n_rows),
        'phase': np.random.choice(['PHASE2', 'PHASE3'], size=n_rows),
        'sponsor_tier': np.random.choice(['TIER_1_GIANT', 'TIER_2_OTHER'], size=n_rows),
        'agency_class': np.random.choice(['INDUSTRY', 'OTHER', 'NIH'], size=n_rows),
        'has_dmc': np.random.choice([0, 1], size=n_rows),
        'is_fda_regulated_drug': np.random.choice([0, 1], size=n_rows),
        'includes_us': np.random.choice([0, 1], size=n_rows),
        'gender': np.random.choice(['All', 'Female', 'Male'], size=n_rows),
        'healthy_volunteers': np.random.choice(['No', 'Yes'], size=n_rows),
        'masking': np.random.choice(['Quadruple', 'Double', 'None'], size=n_rows),
        'allocation': np.random.choice(['Randomized', 'N/A'], size=n_rows),
        'intervention_model': np.random.choice(['Parallel', 'Crossover'], size=n_rows),
        'primary_purpose': np.random.choice(['Treatment', 'Prevention'], size=n_rows),
        'is_sick_only': np.random.choice([0, 1], size=n_rows),
        'is_gender_restricted': np.random.choice([0, 1], size=n_rows),
        'child': np.random.choice([0, 1], size=n_rows),
        'adult': np.random.choice([0, 1], size=n_rows),
        'older_adult': np.random.choice([0, 1], size=n_rows),

        # --- High Cardinality (to test Target Encoding) ---
        'therapeutic_area': np.random.choice(['Oncology', 'Cardio', 'Infectious'], size=n_rows),
        'therapeutic_subgroup_name': np.random.choice(['Breast Cancer', 'Hypertension', 'Flu'], size=n_rows),
        'best_pathology': np.random.choice(['Path_A', 'Path_B', 'Path_C'], size=n_rows),
        'sponsor_clean': np.random.choice(['Pfizer', 'Novartis', 'SmallBio'], size=n_rows),
    }

    # Add Embeddings
    for i in range(100):
        data[f'emb_{i}'] = np.random.normal(0, 1, size=n_rows)

    df = pd.DataFrame(data)

    # Create Target (correlated with agent_category for testing)
    # If agent is KINASE, higher chance of failure (1)
    y = df['agent_category'].apply(lambda x: 1 if x == 'KINASE_INHIBITOR' else 0)

    return df, y

def audit_pipeline():
    print(">>> 1. Generating Mock Data...")
    df_raw, y = generate_realistic_mock_data(n_rows=10)
    print(f"    Raw Data Shape: {df_raw.shape}")

    print("\n>>> 2. Fitting Pipeline...")
    pp = get_preprocessor()
    X_processed = pp.fit_transform(df_raw, y)

    print("\n>>> 3. Reconstructing Feature Names...")
    # This retrieves the names generated by OneHotEncoder, etc.
    feature_names = pp.get_feature_names_out()

    # Create a readable DataFrame
    df_processed = pd.DataFrame(X_processed, columns=feature_names)
    print(f"    Processed Data Shape: {df_processed.shape}")
    print(f"    Columns Created: {len(feature_names)}")

    print("\n" + "="*60)
    print(" AUDIT REPORT: BEFORE vs AFTER")
    print("="*60)

    # --- CHECK 1: LOG SCALING ---
    print("\n[CHECK 1] Log1p + Scaling (Example: competition_broad)")
    raw_vals = df_raw['competition_broad'].head(3).values
    proc_col = [c for c in feature_names if 'competition_broad' in c][0]
    proc_vals = df_processed[proc_col].head(3).values

    for r, p in zip(raw_vals, proc_vals):
        print(f"   Original: {r:8.2f}  ->  Processed: {p:8.4f} (Should be small float)")

    # --- CHECK 2: ONE HOT ENCODING ---
    print("\n[CHECK 2] OneHot Encoding (Example: agent_category)")
    print(f"   Original Value: {df_raw['agent_category'].iloc[0]}")

    # Find columns related to agent_category
    agent_cols = [c for c in feature_names if 'agent_category' in c]
    print("   Active Flags for Row 0:")
    for col in agent_cols:
        val = df_processed[col].iloc[0]
        if val > 0:
            print(f"     -> {col}: {val}")

    # --- CHECK 3: TARGET ENCODING ---
    print("\n[CHECK 3] Target Encoding (Example: therapeutic_area)")
    print(f"   Original Value: {df_raw['therapeutic_area'].iloc[0]}")
    target_col = [c for c in feature_names if 'therapeutic_area' in c][0]
    print(f"   Processed Value: {df_processed[target_col].iloc[0]:.4f} (Should be a probability 0-1)")

    # --- CHECK 4: EMBEDDINGS ---
    print("\n[CHECK 4] Embeddings (Example: emb_0)")
    print(f"   Original: {df_raw['emb_0'].iloc[0]:.4f}")
    emb_col = [c for c in feature_names if 'emb_0' in c][0]
    print(f"   Processed: {df_processed[emb_col].iloc[0]:.4f} (Should be Scaled)")

    print("\n" + "="*60)
    print(">>> AUDIT COMPLETE. PIPELINE IS HEALTHY.")

if __name__ == "__main__":
    audit_pipeline()
