import joblib
import pandas as pd
import numpy as np
import os

def inspect_trained_model():
    # 1. Load the Saved Model
    model_path = os.path.join(os.path.dirname(__file__), '../models/xgb_model.joblib')

    if not os.path.exists(model_path):
        print(f"Error: Model not found at {model_path}")
        print("Run 'python train_model.py' first!")
        return

    print(f">>> Loading model from: {model_path}")
    pipeline = joblib.load(model_path)

    # 2. Extract Steps
    # The pipeline has steps named 'preprocessor' and 'classifier' (defined in train_model.py)
    preprocessor = pipeline.named_steps['preprocessor']
    classifier = pipeline.named_steps['classifier']

    # 3. Get Feature Names (The "All Columns" List)
    # This retrieves the names generated by OneHot, LogScaler, etc.
    try:
        feature_names = preprocessor.get_feature_names_out()
        print(f"    Total Features (Columns) Used: {len(feature_names)}")
    except AttributeError:
        print("Error: Could not retrieve feature names. Ensure scikit-learn >= 1.2")
        return

    # 4. Get Feature Importance (The "Audit")
    # XGBoost provides .feature_importances_
    importances = classifier.feature_importances_

    # 5. Combine into a Readable Table
    df_audit = pd.DataFrame({
        'feature_name': feature_names,
        'importance': importances
    })

    # Sort by Importance (Highest first)
    df_audit = df_audit.sort_values(by='importance', ascending=False).reset_index(drop=True)

    # 6. Display the "Top 20" Drivers
    print("\n" + "="*60)
    print(" TOP 20 PREDICTIVE FEATURES (The Model's Brain)")
    print("="*60)
    print(df_audit.head(20).to_string(index=False))

    # 7. Save Full Audit to CSV (So you can see ALL columns)
    output_path = os.path.join(os.path.dirname(__file__), '../models/feature_importance_audit.csv')
    df_audit.to_csv(output_path, index=False)
    print("\n" + "="*60)
    print(f">>> Full feature list saved to: {output_path}")
    print("    Open this CSV to see every single column created.")

if __name__ == "__main__":
    inspect_trained_model()
